### ISSUE TITLE
Bug with Custom Color in Demo and missing rotation handling

### ISSUE THREAD

**Issue by winkelsdorf** [macfeteria/JKNotificationPanel#3]
Looks great, thanks for publishing!

Two bugs I noticed when trying the demo:
- Text for Custom Color is positioned slightly off the center. "Success with 
  custom color" should be a little lower.

<img width="515" alt="screenshot 2016-03-26 22 47 35" src="https://cloud.githubusercontent.com/assets/1413291/14062608/34163136-f3a5-11e5-9494-c6cbc7e62c61.png">

<img width="513" alt="screenshot 2016-03-26 22 47 37" src="https://cloud.githubusercontent.com/assets/1413291/14062609/34169b80-f3a5-11e5-8eab-06ba3b382048.png">
- Rotation handling is not implemented at all:

<img width="862" alt="screenshot 2016-03-26 22 48 57" src="https://cloud.githubusercontent.com/assets/1413291/14062611/534e5740-f3a5-11e5-8630-094b9e014c10.png">

Basic resizing should be easy to implement using autoResizingMask [.FlexibleWidth, .FlexibleHeight] for the bannerView and Label with translatesAutoresizingMaskIntoConstraints = true. Regarding the position, looks like a constraints to topLayout is needed.. UINavigationBar usually resizes upon rotation.

Cheers,
Frederik

**Comment by macfeteria** [comment]
OK, Thanks for your feedback.
I will fix this issue soon.

**Comment by winkelsdorf** [comment]
You're welcome! Thanks for the great work :+1:

**Comment by macfeteria** [comment]
Fixed.

**Comment by winkelsdorf** [comment]
Thank you very much! 

Confirming this works excellent, even with iPad using Split View Mode 👍
