### ISSUE TITLE
Linebreak not working when used in UISplitViewController 

### ISSUE THREAD

**Issue by winkelsdorf** [macfeteria/JKNotificationPanel#5]
Hi again,

sorry to bother you again and again. I am trying to use this productive, so I stumble about some issues during testing.

When using JKNotificationPanel with a long text (as in the demo), the text is cut off when being using in a UISplitViewController's DetailView:

<img width="658" alt="screenshot 2016-04-12 13 21 59" src="https://cloud.githubusercontent.com/assets/1413291/14458633/c928c0f8-00b2-11e6-94bf-980d30bbd11e.png">

Should be "Offline Mode: Detailed product information, images and datasheets are not available when offline."

Edit: Rotation height is broken too, when used in a UISplitVC. After rotation the Panel is cut of at the top (a few pixels).

**How to reproduce**:
Create UISplitViewController from Xcode project templates, add JKNotification Panel to Detail View. Try to show a long text and/or rotate. Best seen when setting `.AllVisible` property of SplitView (`splitViewController.preferredDisplayMode = UISplitViewControllerDisplayMode.AllVisible`), so the Master View does not hide when shown portrait on iPad.

Any idea?

**Comment by macfeteria** [comment]
When rotate the view it should resize the text view.
but I didn't test it on UISplitView.

I'm going to fix this.

**Comment by macfeteria** [comment]
I fixed the issue.
You may need to change some code
Please check the iPad demo project. 
The rotation and resize should work with iPad & iPhone.
