### ISSUE TITLE
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: JKNotificationPanel-library

### ISSUE THREAD

**Issue by johndpope** [macfeteria/JKNotificationPanel#8]
this looks like the best library available. 
(Although looking to integrate this into an existing project - it's a shame you don't support a title + message.)

➜  Example pod install

[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `JKNotificationPanel-iPhone`..

 #  from /Users/johndpope/Downloads/github.com/JKNotificationPanel-master/Example/Podfile:4
 #  -------------------------------------------
 #

>  target 'JKNotificationPanel-iPhone', :exclusive => true do
>  #    pod "JKNotificationPanel", :path => "../"
>  #  -------------------------------------------

fyi https://github.com/bryx-inc/BRYXBanner

**Comment by macfeteria** [comment]
Hi, thanks for feed back I will fix this issue and release the new version soon.

**Comment by macfeteria** [comment]
version 1.0.0 support title + message.
